"""empty message

Revision ID: 2765b491890c
Revises: 190163627111
Create Date: 2018-07-22 17:05:32.885474

"""

# revision identifiers, used by Alembic.
revision = '2765b491890c'
down_revision = '190163627111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
